[package]
name = "smsru-examples"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "send_sms"
path = "send_sms.rs"

[dependencies]
smsru = { path = ".." }
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }
